# Generated by Django 4.2.1 on 2023-05-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_institute_remove_user_type_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
