# Generated by Django 4.1.1 on 2023-06-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_institute_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
