# Generated by Django 4.1.1 on 2023-06-25 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_alter_institute_description_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.institute')),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.user')),
            ],
        ),
    ]
