# Generated by Django 4.2.1 on 2023-07-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_post_user_alter_follows_followers_delete_user'),
        ('feed', '0011_alter_post_creator'),
    ]

    operations = [
    ]
