# Generated by Django 4.2.1 on 2023-07-15 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0015_alter_post_image_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='{% static posts %}'),
        ),
    ]
