# Generated by Django 4.2.3 on 2023-07-17 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0018_profile_alter_post_text_delete_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 16, 23, 30, 25, 997341)),
        ),
    ]
